export default {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    LOGOUT: 'USERS_LOGOUT',

    USER_FETCH_PROFILE_REQUEST: 'USERS_FETCH_PROFILE_REQUEST',
    USER_FETCH_PROFILE_SUCCESS: 'USERS_FETCH_PROFILE_SUCCESS',

    USER_PATCH_REQUEST: 'USERS_PATCH_REQUEST',
    USER_PATCH_SUCCESS: 'USERS_PATCH_SUCCESS',
};